### ISSUE TITLE
Pencil v3 not working 

### ISSUE THREAD

**Issue by musisam** [evolus/pencil#350]
* Operating system: windows 8 and 10
* Pencil version:3.03

I am getting a blank screen on both operating systems please advise me on what to do to get pencil running.

**Comment by medicationforall** [comment]
Same 
* windows 10
* Pencil Version: 3.04

Application starts with the pencil logo pulsating in the center, and never gets any farther.

**Comment by dgthanhan** [comment]
Pencil may get stuck at loading the libraries. Please try to open the developer console at that screen by pressing Ctrl + Alt + Shift + P

If that does not work, try to open Pencil in developer mode by navigating to the installation directory where you can locate the Pencil.exe, open the command line prompt inside that directry and run the following command:

`Pencil.exe --enable-dev`

When you are at the developer console, please copy the full log into this issue so that I can see what went wrong.

**Comment by h1z1** [comment]
Wish I knew that earlier!   As per #363 I've been unable to get Pencil v3 working...until now.  I have no idea why that key combination made it work nor why Pencil now works  on startup  ??

**Comment by AerandirSurion** [comment]
The pressing combination doesn't work for me (on Windows 7 x64).

After enabling console, here the error I get: 

`util.js:1026 Uncaught (in promise) Error: spawn UNKNOWN(…)exports._errnoException @ util.js:1026ChildProcess.spawn @ internal/child_process.js:313exports.spawn @ child_process.js:392exports.execFile @ child_process.js:155module.(anonymous function) @ ELECTRON_ASAR.js:219win32 @ C:\Program Files\Pencil\resources\app.asar\desktop.js:131getDesktopFontConfig @ C:\Program Files\Pencil\resources\app.asar\desktop.js:188(anonymous function) @ Common.js:581widget.reloadDesktopFont @ Common.js:580(anonymous function) @ Common.js:649`

**Comment by dgthanhan** [comment]
@AerandirSurion Thanks for the details. For some reasons the native code for enumerating fonts crashed. We are looking into the possible options for this.

**Comment by sdowhaniuk** [comment]
experiencing same 'pulsating P' issue on startup. program wont start. Windows 7, with Office 2016.

1 console shows util.js:366 as null... " console.log(isIE);"

2 console shows a warning as:
"Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/."  

util.js:475 is the line of code throwing the warning:  "request.open("GET", relPath, false);"
"GET" is red.

3 final console item is error is mentioned above by AerandirSurion. 
util.js:1026 is the line of code throwing the error:  " var e = new Error(message);"

**Comment by outgoing94** [comment]
Why do i keep getting these emails?

**Comment by dgthanhan** [comment]
@sdowhaniuk Those are not related to this issue.

**Comment by 242Xtro** [comment]
still have the same problem.... installed Pencil,..it stucks with a blank screen...

**Comment by naturtrunken** [comment]
Same here with macOS Sierra 10.12.5 (and 10.12.6) with Pencil 3.0.0, 3.0.1, 3.0.2 and 3.0.4. 

No interesting output on the console:
> ./Pencil --enable-dev
> Background web-printer started.
> RENDERER started.

Here a screenshot of 3.0.4:
![pencil304](https://user-images.githubusercontent.com/2157768/29018927-3dda5468-7b5d-11e7-9260-c69b84f057fd.png)

I deleted the ~/.pencil directory also. And I'm a little bit confused because Pencil 3.0.(1|2) was running ~ a month ago. Maybe the bug has a connection to a webkit/chome update? Anyway I don't understand why old versions also not running anymore.

**Comment by naturtrunken** [comment]
The same errors appear on a Debian-based live system, but Pencil works there. (I tried now the current master branch on Mac and Linux.)

![pencil304lin](https://user-images.githubusercontent.com/2157768/29020830-943793ce-7b63-11e7-9e8a-80be8d4cf27d.png)

Would be interesting to know if the current Pencil version works on Windows or Mac systems which haven't the latest os/chrome version.

**Comment by LukeTully** [comment]
These errors have been happening since at least as far back as Jan 27th (#236), but more likely since mid-2016. I put some time into trying to resolve the issues to no avail.

**Comment by heitara** [comment]
I have the same problem (macOS 10.12.6) . I've checked the latest version from github, still blank screen. I'm seeing the following error:

util.js:1355 Error: ENOENT: no such file or directory, stat '/Users/emil/.pencil/privateCollection/Inline image 1.xml'(…)Console.dumpError @ util.js:1355PrivateCollectionManager.loadPrivateCollections @ privateCollectionManager.js:31MyCollectionPane.initialize @ MyCollectionPane.js:22BaseCollectionPane @ BaseCollectionPane.js:93MyCollectionPane @ MyCollectionPane.js:2(anonymous function) @ Common.js:174Dom.doOnChildRecursively @ util.js:664performAutoBinding @ Common.js:159(anonymous function) @ Common.js:219Dom.doOnChildRecursively @ util.js:664Dom.doOnChildRecursively @ util.js:665Dom.doOnChildRecursively @ util.js:665performAutoBinding @ Common.js:159_processTemplate @ Common.js:234_toTemplateNode @ Common.js:361loadTemplateAsNodeSync @ Common.js:372BaseTemplatedWidget.buildDOMNode @ Common.js:840BaseWidget @ Common.js:654BaseTemplatedWidget @ Common.js:834ApplicationPane @ ApplicationPane.js:2(anonymous function) @ Common.js:174Dom.doOnChildRecursively @ util.js:664performAutoBinding @ Common.js:159onLoadDone @ Common.js:606loadNext @ Common.js:617request.onreadystatechange @ Common.js:641
shapeDefCollectionParser.js:47 GET file:///Users/emil/Documents/Projects/NodeJS/pencil/app/stencils/Common/en-US.dtd ShapeDefCollectionParser.injectEntityDefsFromUrl @ shapeDefCollectionParser.js:47ShapeDefCollectionParser.parseURL @ shapeDefCollectionParser.js:71CollectionManager.loadStencils @ collectionManager.js:205Pencil.boot@ pencil.js:89ApplicationPane @ ApplicationPane.js:4(anonymous function) @ Common.js:174Dom.doOnChildRecursively @ util.js:664performAutoBinding @ Common.js:159onLoadDone @ Common.js:606loadNext @ Common.js:617request.onreadystatechange @ Common.js:641

**Comment by LukeTully** [comment]
One thing that would really help contribution to solving things like this
is a well documented code base. If memory serves, last I tried diving into
this there weren’t comments or a direct pathway through the code that I
might follow and isolate the issue. Previously in this thread and in my
issue’s thread it was mentioned that you can start up the app in dev mode
and that none of the devs use macs. Things like that would be very useful
to document so that potentiontial contributors know where to start.

Luke Tully
604-445-9823

From: Emil <notifications@github.com> <notifications@github.com>
Reply: evolus/pencil
<reply@reply.github.com>
<reply@reply.github.com>
Date: August 23, 2017 at 7:49:11 AM
To: evolus/pencil <pencil@noreply.github.com> <pencil@noreply.github.com>
Cc: Luke Tully <luke@luketully.ca> <luke@luketully.ca>, Comment
<comment@noreply.github.com> <comment@noreply.github.com>
Subject:  Re: [evolus/pencil] Pencil v3 not working (#350)

I have the same problem (macOS 10.12.6) . I've checked the latest version
from github, still blank screen. I'm seeing the following error:

util.js:1355 Error: ENOENT: no such file or directory, stat
'/Users/emil/.pencil/privateCollection/Inline image
1.xml'(…)Console.dumpError @
util.js:1355PrivateCollectionManager.loadPrivateCollections @
privateCollectionManager.js:31MyCollectionPane.initialize @
MyCollectionPane.js:22BaseCollectionPane @
BaseCollectionPane.js:93MyCollectionPane @ MyCollectionPane.js:2(anonymous
function) @ Common.js:174Dom.doOnChildRecursively @
util.js:664performAutoBinding @ Common.js:159(anonymous function) @
Common.js:219Dom.doOnChildRecursively @ util.js:664Dom.doOnChildRecursively
@ util.js:665Dom.doOnChildRecursively @ util.js:665performAutoBinding @
Common.js:159_processTemplate @ Common.js:234_toTemplateNode @
Common.js:361loadTemplateAsNodeSync @
Common.js:372BaseTemplatedWidget.buildDOMNode @ Common.js:840BaseWidget @
Common.js:654BaseTemplatedWidget @ Common.js:834ApplicationPane @
ApplicationPane.js:2(anonymous function) @
Common.js:174Dom.doOnChildRecursively @ util.js:664performAutoBinding @
Common.js:159onLoadDone @ Common.js:606loadNext @
Common.js:617request.onreadystatechange @ Common.js:641
shapeDefCollectionParser.js:47 GET
file:///Users/emil/Documents/Projects/NodeJS/pencil/app/stencils/Common/en-US.dtd
ShapeDefCollectionParser.injectEntityDefsFromUrl @
shapeDefCollectionParser.js:47ShapeDefCollectionParser.parseURL @
shapeDefCollectionParser.js:71CollectionManager.loadStencils @
collectionManager.js:205Pencil.boot@ pencil.js:89ApplicationPane @
ApplicationPane.js:4(anonymous function) @
Common.js:174Dom.doOnChildRecursively @ util.js:664performAutoBinding @
Common.js:159onLoadDone @ Common.js:606loadNext @
Common.js:617request.onreadystatechange @ Common.js:641

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/evolus/pencil/issues/350#issuecomment-324318925>, or mute
the thread

**Comment by h1z1** [comment]
Had this happen again today.   Restarting pencil with --enable-dev as per above made it work again..  No idea why.

**Comment by LukeTully** [comment]
@h1z1 I was only able to get as far as it crashing with the devtools open.

**Comment by devistar** [comment]
I have the same problem. This version is not stable.
I started a mock and I cannot continue working on it. It is frustrating. 
Please fix it.

**Comment by hardise** [comment]
in this link find and install (Pencil-2.0.5.win32.installer.exe)
it's work in Windows 10 pro
https://code.google.com/archive/p/evoluspencil/downloads

**Comment by h-2-0** [comment]
Same here. Not working. Intermittent logo then just blank page. 

Debian 7.  Installed using both __Pencil_3.0.4_i386.deb__ and __git clone__ (with nodejs v6) approaches.  Got same result: blank page.  

This is what I get (25 errors) when I run `./node_modules/.bin/electron ./app --enable-dev --disable-gpu`
```
util.js:366 null
util.js:475 Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
desktop.js:78 Coud not found font command registry for  gnome-fallbacklinux @ desktop.js:78getDesktopFontConfig @ desktop.js:188(anonymous function) @ Common.js:581widget.reloadDesktopFont @ Common.js:580(anonymous function) @ Common.js:649
Common.js:646 GET file:///home/user/opt/pencil/app/views/common/BuilderBasedDialog.xhtml?t=1515500519399_8348 net::ERR_FILE_NOT_FOUNDloadNext @ Common.js:646request.onreadystatechange @ Common.js:641
Common.js:646 GET file:///home/user/opt/pencil/app/views/common/ToolBar.xhtml?t=1515500519399_8348 net::ERR_FILE_NOT_FOUNDloadNext @ Common.js:646request.onreadystatechange @ Common.js:641
Common.js:646 GET file:///home/user/opt/pencil/app/views/common/WizardDialog.xhtml?t=1515500519399_8348 net::ERR_FILE_NOT_FOUNDloadNext @ Common.js:646request.onreadystatechange @ Common.js:641
Common.js:646 GET file:///home/user/opt/pencil/app/views/editors/PropertyEditor.xhtml?t=1515500519399_8348 net::ERR_FILE_NOT_FOUNDloadNext @ Common.js:646request.onreadystatechange @ Common.js:641
Common.js:646 GET file:///home/user/opt/pencil/app/views/menus/CanvasMenu.xhtml?t=1515500519399_8348 net::ERR_FILE_NOT_FOUNDloadNext @ Common.js:646request.onreadystatechange @ Common.js:641
Common.js:646 GET file:///home/user/opt/pencil/app/views/menus/MainMenu.xhtml?t=1515500519399_8348 net::ERR_FILE_NOT_FOUNDloadNext @ Common.js:646request.onreadystatechange @ Common.js:641
Common.js:646 GET file:///home/user/opt/pencil/app/views/menus/PageMenu.xhtml?t=1515500519399_8348 net::ERR_FILE_NOT_FOUNDloadNext @ Common.js:646request.onreadystatechange @ Common.js:641
Common.js:646 GET file:///home/user/opt/pencil/app/views/menus/ChildPageListMenu.xhtml?t=1515500519399_8348 net::ERR_FILE_NOT_FOUNDloadNext @ Common.js:646request.onreadystatechange @ Common.js:641
Common.js:646 GET file:///home/user/opt/pencil/app/views/collections/CollectionMenu.xhtml?t=1515500519399_8348 net::ERR_FILE_NOT_FOUNDloadNext @ Common.js:646request.onreadystatechange @ Common.js:641
Common.js:646 GET file:///home/user/opt/pencil/app/views/collections/CollectionPane.xhtml?t=1515500519399_8348 net::ERR_FILE_NOT_FOUNDloadNext @ Common.js:646request.onreadystatechange @ Common.js:641
Common.js:646 GET file:///home/user/opt/pencil/app/views/collections/MyCollectionPane.xhtml?t=1515500519399_8348 net::ERR_FILE_NOT_FOUNDloadNext @ Common.js:646request.onreadystatechange @ Common.js:641
Common.js:646 GET file:///home/user/opt/pencil/app/views/collections/PrivateCollectionMenu.xhtml?t=1515500519399_8348 net::ERR_FILE_NOT_FOUNDloadNext @ Common.js:646request.onreadystatechange @ Common.js:641
Common.js:646 GET file:///home/user/opt/pencil/app/views/collections/ShowAllCollectionMenu.xhtml?t=1515500519399_8348 net::ERR_FILE_NOT_FOUNDloadNext @ Common.js:646request.onreadystatechange @ Common.js:641
util.js:1355 Error: ENOENT: no such file or directory, stat '/home/user/.pencil/privateCollection/PrivateCollection.xml'(…)Console.dumpError @ util.js:1355PrivateCollectionManager.loadPrivateCollections @ privateCollectionManager.js:31MyCollectionPane.initialize @ MyCollectionPane.js:22BaseCollectionPane @ BaseCollectionPane.js:93MyCollectionPane @ MyCollectionPane.js:2(anonymous function) @ Common.js:174Dom.doOnChildRecursively @ util.js:664performAutoBinding @ Common.js:159(anonymous function) @ Common.js:219Dom.doOnChildRecursively @ util.js:664Dom.doOnChildRecursively @ util.js:665Dom.doOnChildRecursively @ util.js:665performAutoBinding @ Common.js:159_processTemplate @ Common.js:234_toTemplateNode @ Common.js:361loadTemplateAsNodeSync @ Common.js:372BaseTemplatedWidget.buildDOMNode @ Common.js:840BaseWidget @ Common.js:654BaseTemplatedWidget @ Common.js:834ApplicationPane @ ApplicationPane.js:2(anonymous function) @ Common.js:174Dom.doOnChildRecursively @ util.js:664performAutoBinding @ Common.js:159onLoadDone @ Common.js:606loadNext @ Common.js:617request.onreadystatechange @ Common.js:641
shapeDefCollectionParser.js:47 GET file:///home/user/opt/pencil/app/stencils/Common/en-US.dtd ShapeDefCollectionParser.injectEntityDefsFromUrl @ shapeDefCollectionParser.js:47ShapeDefCollectionParser.parseURL @ shapeDefCollectionParser.js:71CollectionManager.loadStencils @ collectionManager.js:205Pencil.boot @ pencil.js:89ApplicationPane @ ApplicationPane.js:4(anonymous function) @ Common.js:174Dom.doOnChildRecursively @ util.js:664performAutoBinding @ Common.js:159onLoadDone @ Common.js:606loadNext @ Common.js:617request.onreadystatechange @ Common.js:641
shapeDefCollectionParser.js:47 GET file:///home/user/opt/pencil/app/stencils/BasicWebElements/en-US.dtd ShapeDefCollectionParser.injectEntityDefsFromUrl @ shapeDefCollectionParser.js:47ShapeDefCollectionParser.parseURL @ shapeDefCollectionParser.js:71CollectionManager.loadStencils @ collectionManager.js:206Pencil.boot @ pencil.js:89ApplicationPane @ ApplicationPane.js:4(anonymous function) @ Common.js:174Dom.doOnChildRecursively @ util.js:664performAutoBinding @ Common.js:159onLoadDone @ Common.js:606loadNext @ Common.js:617request.onreadystatechange @ Common.js:641
shapeDefCollectionParser.js:47 GET file:///home/user/opt/pencil/app/stencils/Gtk.GUI/en-US.dtd ShapeDefCollectionParser.injectEntityDefsFromUrl @ shapeDefCollectionParser.js:47ShapeDefCollectionParser.parseURL @ shapeDefCollectionParser.js:71CollectionManager.loadStencils @ collectionManager.js:207Pencil.boot @ pencil.js:89ApplicationPane @ ApplicationPane.js:4(anonymous function) @ Common.js:174Dom.doOnChildRecursively @ util.js:664performAutoBinding @ Common.js:159onLoadDone @ Common.js:606loadNext @ Common.js:617request.onreadystatechange @ Common.js:641
shapeDefCollectionParser.js:47 GET file:///home/user/opt/pencil/app/stencils/SketchyGUI/en-US.dtd ShapeDefCollectionParser.injectEntityDefsFromUrl @ shapeDefCollectionParser.js:47ShapeDefCollectionParser.parseURL @ shapeDefCollectionParser.js:71CollectionManager.loadStencils @ collectionManager.js:208Pencil.boot @ pencil.js:89ApplicationPane @ ApplicationPane.js:4(anonymous function) @ Common.js:174Dom.doOnChildRecursively @ util.js:664performAutoBinding @ Common.js:159onLoadDone @ Common.js:606loadNext @ Common.js:617request.onreadystatechange @ Common.js:641
shapeDefCollectionParser.js:47 GET file:///home/user/opt/pencil/app/stencils/WindowsXP-GUI/en-US.dtd ShapeDefCollectionParser.injectEntityDefsFromUrl @ shapeDefCollectionParser.js:47ShapeDefCollectionParser.parseURL @ shapeDefCollectionParser.js:71CollectionManager.loadStencils @ collectionManager.js:209Pencil.boot @ pencil.js:89ApplicationPane @ ApplicationPane.js:4(anonymous function) @ Common.js:174Dom.doOnChildRecursively @ util.js:664performAutoBinding @ Common.js:159onLoadDone @ Common.js:606loadNext @ Common.js:617request.onreadystatechange @ Common.js:641
shapeDefCollectionParser.js:47 GET file:///home/user/opt/pencil/app/stencils/CommonShapes_Flowchart/en-US.dtd ShapeDefCollectionParser.injectEntityDefsFromUrl @ shapeDefCollectionParser.js:47ShapeDefCollectionParser.parseURL @ shapeDefCollectionParser.js:71CollectionManager.loadStencils @ collectionManager.js:211Pencil.boot @ pencil.js:89ApplicationPane @ ApplicationPane.js:4(anonymous function) @ Common.js:174Dom.doOnChildRecursively @ util.js:664performAutoBinding @ Common.js:159onLoadDone @ Common.js:606loadNext @ Common.js:617request.onreadystatechange @ Common.js:641
shapeDefCollectionParser.js:47 GET file:///home/user/opt/pencil/app/stencils/Android.GUI/en-US.dtd ShapeDefCollectionParser.injectEntityDefsFromUrl @ shapeDefCollectionParser.js:47ShapeDefCollectionParser.parseURL @ shapeDefCollectionParser.js:71CollectionManager.loadStencils @ collectionManager.js:212Pencil.boot @ pencil.js:89ApplicationPane @ ApplicationPane.js:4(anonymous function) @ Common.js:174Dom.doOnChildRecursively @ util.js:664performAutoBinding @ Common.js:159onLoadDone @ Common.js:606loadNext @ Common.js:617request.onreadystatechange @ Common.js:641
shapeDefCollectionParser.js:47 GET file:///home/user/opt/pencil/app/stencils/iOS.GUI/en-US.dtd ShapeDefCollectionParser.injectEntityDefsFromUrl @ shapeDefCollectionParser.js:47ShapeDefCollectionParser.parseURL @ shapeDefCollectionParser.js:71CollectionManager.loadStencils @ collectionManager.js:213Pencil.boot @ pencil.js:89ApplicationPane @ ApplicationPane.js:4(anonymous function) @ Common.js:174Dom.doOnChildRecursively @ util.js:664performAutoBinding @ Common.js:159onLoadDone @ Common.js:606loadNext @ Common.js:617request.onreadystatechange @ Common.js:641
shapeDefCollectionParser.js:47 GET file:///home/user/opt/pencil/app/stencils/iOS-Wireframe/en-US.dtd ShapeDefCollectionParser.injectEntityDefsFromUrl @ shapeDefCollectionParser.js:47ShapeDefCollectionParser.parseURL @ shapeDefCollectionParser.js:71CollectionManager.loadStencils @ collectionManager.js:214Pencil.boot @ pencil.js:89ApplicationPane @ ApplicationPane.js:4(anonymous function) @ Common.js:174Dom.doOnChildRecursively @ util.js:664performAutoBinding @ Common.js:159onLoadDone @ Common.js:606loadNext @ Common.js:617request.onreadystatechange @ Common.js:641
shapeDefCollectionParser.js:47 GET file:///home/user/opt/pencil/app/stencils/Prototype_GUI/en-US.dtd ShapeDefCollectionParser.injectEntityDefsFromUrl @ shapeDefCollectionParser.js:47ShapeDefCollectionParser.parseURL @ shapeDefCollectionParser.js:71CollectionManager.loadStencils @ collectionManager.js:216Pencil.boot @ pencil.js:89ApplicationPane @ ApplicationPane.js:4(anonymous function) @ Common.js:174Dom.doOnChildRecursively @ util.js:664performAutoBinding @ Common.js:159onLoadDone @ Common.js:606loadNext @ Common.js:617request.onreadystatechange @ Common.js:641
```

**Comment by h-2-0** [comment]
Checked all previous release work starting from the latest (3.0.4, 3.0.3....) and found that the 3.0.0.-rc.2 works!

**Comment by chetnakalia1** [comment]
util.js:366 null
util.js:475 Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
C:\Program Files\Pencil\resources\app.asar\desktop.js:137 System Font: DPI: 96
FontName: Segoe UI
FontSize: 11
FontWeight: 400
FontStyle: normal
Common.js:646 GET file:///C:/Program%20Files/Pencil/resources/app.asar/views/common/BuilderBasedDialog.xhtml?t=1515587123762_4451 net::ERR_FILE_NOT_FOUNDloadNext @ Common.js:646request.onreadystatechange @ Common.js:641
Common.js:646 GET file:///C:/Program%20Files/Pencil/resources/app.asar/views/common/ToolBar.xhtml?t=1515587123762_4451 net::ERR_FILE_NOT_FOUNDloadNext @ Common.js:646request.onreadystatechange @ Common.js:641
Common.js:646 GET file:///C:/Program%20Files/Pencil/resources/app.asar/views/common/WizardDialog.xhtml?t=1515587123762_4451 net::ERR_FILE_NOT_FOUNDloadNext @ Common.js:646request.onreadystatechange @ Common.js:641
Common.js:646 GET file:///C:/Program%20Files/Pencil/resources/app.asar/views/editors/PropertyEditor.xhtml?t=1515587123762_4451 net::ERR_FILE_NOT_FOUNDloadNext @ Common.js:646request.onreadystatechange @ Common.js:641
Common.js:646 GET file:///C:/Program%20Files/Pencil/resources/app.asar/views/menus/CanvasMenu.xhtml?t=1515587123762_4451 net::ERR_FILE_NOT_FOUNDloadNext @ Common.js:646request.onreadystatechange @ Common.js:641
Common.js:646 GET file:///C:/Program%20Files/Pencil/resources/app.asar/views/menus/MainMenu.xhtml?t=1515587123762_4451 net::ERR_FILE_NOT_FOUNDloadNext @ Common.js:646request.onreadystatechange @ Common.js:641
Common.js:646 GET file:///C:/Program%20Files/Pencil/resources/app.asar/views/menus/PageMenu.xhtml?t=1515587123762_4451 net::ERR_FILE_NOT_FOUNDloadNext @ Common.js:646request.onreadystatechange @ Common.js:641
Common.js:646 GET file:///C:/Program%20Files/Pencil/resources/app.asar/views/menus/ChildPageListMenu.xhtml?t=1515587123762_4451 net::ERR_FILE_NOT_FOUNDloadNext @ Common.js:646request.onreadystatechange @ Common.js:641
Common.js:646 GET file:///C:/Program%20Files/Pencil/resources/app.asar/views/collections/CollectionMenu.xhtml?t=1515587123762_4451 net::ERR_FILE_NOT_FOUNDloadNext @ Common.js:646request.onreadystatechange @ Common.js:641
Common.js:646 GET file:///C:/Program%20Files/Pencil/resources/app.asar/views/collections/CollectionPane.xhtml?t=1515587123762_4451 net::ERR_FILE_NOT_FOUNDloadNext @ Common.js:646request.onreadystatechange @ Common.js:641
Common.js:646 GET file:///C:/Program%20Files/Pencil/resources/app.asar/views/collections/MyCollectionPane.xhtml?t=1515587123762_4451 net::ERR_FILE_NOT_FOUNDloadNext @ Common.js:646request.onreadystatechange @ Common.js:641
Common.js:646 GET file:///C:/Program%20Files/Pencil/resources/app.asar/views/collections/PrivateCollectionMenu.xhtml?t=1515587123762_4451 net::ERR_FILE_NOT_FOUNDloadNext @ Common.js:646request.onreadystatechange @ Common.js:641
Common.js:646 GET file:///C:/Program%20Files/Pencil/resources/app.asar/views/collections/ShowAllCollectionMenu.xhtml?t=1515587123762_4451 net::ERR_FILE_NOT_FOUNDloadNext @ Common.js:646request.onreadystatechange @ Common.js:641
util.js:1355 Error: ENOENT: no such file or directory, stat 'C:\Users\Nishant\.pencil\privateCollection\PrivateCollection.xml'(…)Console.dumpError @ util.js:1355PrivateCollectionManager.loadPrivateCollections @ privateCollectionManager.js:31MyCollectionPane.initialize @ MyCollectionPane.js:22BaseCollectionPane @ BaseCollectionPane.js:93MyCollectionPane @ MyCollectionPane.js:2(anonymous function) @ Common.js:174Dom.doOnChildRecursively @ util.js:664performAutoBinding @ Common.js:159(anonymous function) @ Common.js:219Dom.doOnChildRecursively @ util.js:664Dom.doOnChildRecursively @ util.js:665Dom.doOnChildRecursively @ util.js:665performAutoBinding @ Common.js:159_processTemplate @ Common.js:234_toTemplateNode @ Common.js:361loadTemplateAsNodeSync @ Common.js:372BaseTemplatedWidget.buildDOMNode @ Common.js:840BaseWidget @ Common.js:654BaseTemplatedWidget @ Common.js:834ApplicationPane @ ApplicationPane.js:2(anonymous function) @ Common.js:174Dom.doOnChildRecursively @ util.js:664performAutoBinding @ Common.js:159onLoadDone @ Common.js:606loadNext @ Common.js:617request.onreadystatechange @ Common.js:641
shapeDefCollectionParser.js:47 GET file:///C:/Program%20Files/Pencil/resources/app.asar/stencils/Common/en-US.dtd ShapeDefCollectionParser.injectEntityDefsFromUrl @ shapeDefCollectionParser.js:47ShapeDefCollectionParser.parseURL @ shapeDefCollectionParser.js:71CollectionManager.loadStencils @ collectionManager.js:205Pencil.boot @ pencil.js:89ApplicationPane @ ApplicationPane.js:4(anonymous function) @ Common.js:174Dom.doOnChildRecursively @ util.js:664performAutoBinding @ Common.js:159onLoadDone @ Common.js:606loadNext @ Common.js:617request.onreadystatechange @ Common.js:641
shapeDefCollectionParser.js:47 GET file:///C:/Program%20Files/Pencil/resources/app.asar/stencils/BasicWebElements/en-US.dtd ShapeDefCollectionParser.injectEntityDefsFromUrl @ shapeDefCollectionParser.js:47ShapeDefCollectionParser.parseURL @ shapeDefCollectionParser.js:71CollectionManager.loadStencils @ collectionManager.js:206Pencil.boot @ pencil.js:89ApplicationPane @ ApplicationPane.js:4(anonymous function) @ Common.js:174Dom.doOnChildRecursively @ util.js:664performAutoBinding @ Common.js:159onLoadDone @ Common.js:606loadNext @ Common.js:617request.onreadystatechange @ Common.js:641
shapeDefCollectionParser.js:47 GET file:///C:/Program%20Files/Pencil/resources/app.asar/stencils/Gtk.GUI/en-US.dtd ShapeDefCollectionParser.injectEntityDefsFromUrl @ shapeDefCollectionParser.js:47ShapeDefCollectionParser.parseURL @ shapeDefCollectionParser.js:71CollectionManager.loadStencils @ collectionManager.js:207Pencil.boot @ pencil.js:89ApplicationPane @ ApplicationPane.js:4(anonymous function) @ Common.js:174Dom.doOnChildRecursively @ util.js:664performAutoBinding @ Common.js:159onLoadDone @ Common.js:606loadNext @ Common.js:617request.onreadystatechange @ Common.js:641
shapeDefCollectionParser.js:47 GET file:///C:/Program%20Files/Pencil/resources/app.asar/stencils/SketchyGUI/en-US.dtd ShapeDefCollectionParser.injectEntityDefsFromUrl @ shapeDefCollectionParser.js:47ShapeDefCollectionParser.parseURL @ shapeDefCollectionParser.js:71CollectionManager.loadStencils @ collectionManager.js:208Pencil.boot @ pencil.js:89ApplicationPane @ ApplicationPane.js:4(anonymous function) @ Common.js:174Dom.doOnChildRecursively @ util.js:664performAutoBinding @ Common.js:159onLoadDone @ Common.js:606loadNext @ Common.js:617request.onreadystatechange @ Common.js:641
shapeDefCollectionParser.js:47 GET file:///C:/Program%20Files/Pencil/resources/app.asar/stencils/WindowsXP-GUI/en-US.dtd ShapeDefCollectionParser.injectEntityDefsFromUrl @ shapeDefCollectionParser.js:47ShapeDefCollectionParser.parseURL @ shapeDefCollectionParser.js:71CollectionManager.loadStencils @ collectionManager.js:209Pencil.boot @ pencil.js:89ApplicationPane @ ApplicationPane.js:4(anonymous function) @ Common.js:174Dom.doOnChildRecursively @ util.js:664performAutoBinding @ Common.js:159onLoadDone @ Common.js:606loadNext @ Common.js:617request.onreadystatechange @ Common.js:641
shapeDefCollectionParser.js:47 GET file:///C:/Program%20Files/Pencil/resources/app.asar/stencils/CommonShapes_Flowchart/en-US.dtd ShapeDefCollectionParser.injectEntityDefsFromUrl @ shapeDefCollectionParser.js:47ShapeDefCollectionParser.parseURL @ shapeDefCollectionParser.js:71CollectionManager.loadStencils @ collectionManager.js:211Pencil.boot @ pencil.js:89ApplicationPane @ ApplicationPane.js:4(anonymous function) @ Common.js:174Dom.doOnChildRecursively @ util.js:664performAutoBinding @ Common.js:159onLoadDone @ Common.js:606loadNext @ Common.js:617request.onreadystatechange @ Common.js:641
shapeDefCollectionParser.js:47 GET file:///C:/Program%20Files/Pencil/resources/app.asar/stencils/Android.GUI/en-US.dtd ShapeDefCollectionParser.injectEntityDefsFromUrl @ shapeDefCollectionParser.js:47ShapeDefCollectionParser.parseURL @ shapeDefCollectionParser.js:71CollectionManager.loadStencils @ collectionManager.js:212Pencil.boot @ pencil.js:89ApplicationPane @ ApplicationPane.js:4(anonymous function) @ Common.js:174Dom.doOnChildRecursively @ util.js:664performAutoBinding @ Common.js:159onLoadDone @ Common.js:606loadNext @ Common.js:617request.onreadystatechange @ Common.js:641
shapeDefCollectionParser.js:47 GET file:///C:/Program%20Files/Pencil/resources/app.asar/stencils/iOS.GUI/en-US.dtd ShapeDefCollectionParser.injectEntityDefsFromUrl @ shapeDefCollectionParser.js:47ShapeDefCollectionParser.parseURL @ shapeDefCollectionParser.js:71CollectionManager.loadStencils @ collectionManager.js:213Pencil.boot @ pencil.js:89ApplicationPane @ ApplicationPane.js:4(anonymous function) @ Common.js:174Dom.doOnChildRecursively @ util.js:664performAutoBinding @ Common.js:159onLoadDone @ Common.js:606loadNext @ Common.js:617request.onreadystatechange @ Common.js:641
shapeDefCollectionParser.js:47 GET file:///C:/Program%20Files/Pencil/resources/app.asar/stencils/iOS-Wireframe/en-US.dtd ShapeDefCollectionParser.injectEntityDefsFromUrl @ shapeDefCollectionParser.js:47ShapeDefCollectionParser.parseURL @ shapeDefCollectionParser.js:71CollectionManager.loadStencils @ collectionManager.js:214Pencil.boot @ pencil.js:89ApplicationPane @ ApplicationPane.js:4(anonymous function) @ Common.js:174Dom.doOnChildRecursively @ util.js:664performAutoBinding @ Common.js:159onLoadDone @ Common.js:606loadNext @ Common.js:617request.onreadystatechange @ Common.js:641
shapeDefCollectionParser.js:47 GET file:///C:/Program%20Files/Pencil/resources/app.asar/stencils/Prototype_GUI/en-US.dtd ShapeDefCollectionParser.injectEntityDefsFromUrl @ shapeDefCollectionParser.js:47ShapeDefCollectionParser.parseURL @ shapeDefCollectionParser.js:71CollectionManager.loadStencils @ collectionManager.js:216Pencil.boot @ pencil.js:89ApplicationPane @ ApplicationPane.js:4(anonymous function) @ Common.js:174Dom.doOnChildRecursively @ util.js:664performAutoBinding @ Common.js:159onLoadDone @ Common.js:606loadNext @ Common.js:617request.onreadystatechange @ Common.js:641

**Comment by EdouardH** [comment]
Same here, seems a problem with user rights. Blinking logo when user is not Admin in Windows 10:

util.js:1026 Uncaught (in promise) Error: spawn UNKNOWN
    at exports._errnoException (util.js:1026:11)
    at ChildProcess.spawn (internal/child_process.js:313:11)
    at exports.spawn (child_process.js:392:9)
    at exports.execFile (child_process.js:155:15)
    at module.(anonymous function) (ELECTRON_ASAR.js:219:18)
    at win32 (C:\Program Files\Pencil\resources\app.asar\desktop.js:131:25)
    at Object.getDesktopFontConfig (C:\Program Files\Pencil\resources\app.asar\desktop.js:188:9)
    at file:///C:/Program%20Files/Pencil/resources/app.asar/lib/widget/Common.js:581:34
    at Object.widget.reloadDesktopFont (file:///C:/Program%20Files/Pencil/resources/app.asar/lib/widget/Common.js:580:16)
    at XMLDocument.<anonymous> (file:///C:/Program%20Files/Pencil/resources/app.asar/lib/widget/Common.js:649:12)exports._errnoException @ util.js:1026ChildProcess.spawn @ internal/child_process.js:313exports.spawn @ child_process.js:392exports.execFile @ child_process.js:155module.(anonymous function) @ ELECTRON_ASAR.js:219win32 @ C:\Program Files\Pencil\resources\app.asar\desktop.js:131getDesktopFontConfig @ C:\Program Files\Pencil\resources\app.asar\desktop.js:188(anonymous function) @ Common.js:581widget.reloadDesktopFont @ Common.js:580(anonymous function) @ Common.js:649

**Comment by luck9081** [comment]
I have Windows 7 64-bit and managed to go past the white screen by running as administrator. I'm using v3.0.4

**Comment by Kraeven** [comment]
Yep similar here, not an admin windows 10 pro - can't spawn the child process

![image](https://user-images.githubusercontent.com/696633/46803208-d5f52480-cd5f-11e8-8b6c-f99cc4925e92.png)

**Comment by LukeTully** [comment]
I wonder if it’s trying to access privileged files. I’m not too familiar
with how to track that down, but it would most likely help to monitor what
paths it’s trying to access.


On November 22, 2018 at 2:24:52 AM, ITThatRandomGuy (
notifications@github.com) wrote:

Hello Everyone,

It might be worth mentioning that one of my colleagues had the same issue,
so after some investigation I bit the bullet and installed Pencil.EXE on my
PC, and it worked fine, the only difference between me and my colleague is
that i'm the network admin and he has no administrative permissions, not
even local.

So I ran the program from the file source location using my credentials and
it worked without any issues.

Can anyone explain to me why this software needs to be run as an Admin?

Thanks

ITThatRandomGuy

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/evolus/pencil/issues/350#issuecomment-440983911>, or mute
the thread

**Comment by kjetil-kilhavn** [comment]
I had this problem (Windows version) and tried the nightly build pencil-3.0.4.20190410003002-x86_64.exe. In this build it seems the problem has been solved.

**Comment by SlyEzo** [comment]
Same problem here :)
If it can help... on my laptop at home, it works. But when I'm on the client's network, it fails.

**Comment by SlyEzo** [comment]
Good Day :D
Sorry for the last message, but trying to make it work with IT support of my client resulted in a workaround that seems to work.

`Reg Delete HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\safer /f`

This line prevented me from running applications found under the local user folder, including, for example, npm modules installed globally.

**Comment by gaurav-sardana** [comment]
Delete '.pencil file' User/<Your_Name> and restart the pencil.

**Comment by ConstantineFrol** [comment]
Reinstall pencil and still the same problem
It might sound funny, but I tried to run a Pencil as administrator and all start working.
WINDOWS 10
Pencil 3.1.0
